apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: switcher-resolver
  labels:
    {{- include "switcher-resolver.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ randAlphaNum 16 | b64enc | quote }}
  MONGODB_URI: {{ .Values.resolver.env.mongoUri | b64enc | quote }}
  RESOURCE_SECRET: {{ default "admin" .Values.resolver.env.resourceSecret | b64enc | quote }}