apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: switcher-api
  labels:
    {{- include "switcher-api.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ randAlphaNum 16 | b64enc | quote }}
  MONGODB_URI: {{ .Values.api.env.mongoUri | b64enc | quote }}
  RESOURCE_SECRET: {{ default "admin" .Values.api.env.resourceSecret | b64enc | quote }}

  # Auth Integration 
  {{- if and .Values.api.env.bitbucketClientId .Values.api.env.bitbucketClientSecret -}}
  BITBUCKET_OAUTH_SECRET: {{ .Values.api.env.bitbucketClientSecret | b64enc | quote }}
  {{- end -}}
  {{- if and .Values.api.env.githubClientId .Values.api.env.githubClientSecret -}}
  GIT_OAUTH_SECRET: {{ .Values.api.env.githubClientSecret | b64enc | quote }}
  {{- end -}}

  # Platform/Services Integration
  {{- if .Values.api.env.googleRecaptchaSecret -}}
  GOOGLE_RECAPTCHA_SECRET: {{ .Values.api.env.googleRecaptchaSecret | b64enc | quote }}
  {{- end -}}
  {{- if .Values.api.env.switcherSlackJwtSecret -}}
  SWITCHER_SLACK_JWT_SECRET: {{ .Values.api.env.switcherSlackJwtSecret | b64enc | quote }}
  {{- end -}}
  {{- if .Values.api.env.switcherGitOpsJwtSecret -}}
  SWITCHER_GITOPS_JWT_SECRET: {{ .Values.api.env.switcherGitOpsJwtSecret | b64enc | quote }}
  {{- end -}}