apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: switcher-api
  labels:
    {{- include "switcher-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "switcher-api.selectorLabels" . | nindent 4 }}
