apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: switcher-gitops
  labels:
    {{- include "switcher-gitops.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_URI: {{ .Values.app.env.mongoUri | b64enc | quote }}
  MONGO_DB: {{ .Values.app.env.mongoDb | b64enc | quote }}
  GIT_TOKEN_PRIVATE_KEY: {{ .Values.app.env.gitTokenPrivateKey | b64enc | quote }}
  SWITCHER_API_JWT_SECRET: {{ .Values.app.env.switcherApiJwtSecret | b64enc | quote }}