apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: switcher-management
  labels:
    {{- include "switcher-management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.management.service.type }}
  ports:
    - name: http
      port: {{ .Values.management.service.port }}
      targetPort: http
      protocol: TCP
    - name: https
      protocol: TCP
      port: {{ .Values.management.service.portTls }}
      targetPort: {{ .Values.management.service.portTls }}
  selector:
    {{- include "switcher-management.selectorLabels" . | nindent 4 }}
