apiVersion: v2
name: switcher-slack-app
home: https://github.com/switcherapi/helm-charts
description: A Switcher Slack App Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/switcherapi/switcherapi-assets/master/logo/switcher_mark_grey.png
maintainers:
  - name: petruki
    email: switcher.project@gmail.com
    url: https://github.com/petruki

type: application
version: 1.1.3
appVersion: "latest"
