app:
  replicaCount: 1
  port: 5000

  env:
    slackClientId: ""
    switcherManagementUrl: "https://cloud.switcherapi.com"
    switcherAPIUrl: "https://switcherapi.com/api"

    # Enable SSL
    sslSecretName: ""
    switcherCertPath: ""

  image:
    repository: trackerforce/switcher-slack-app
    pullPolicy: IfNotPresent
    tag: "latest"

  envFrom:
  - configMapRef:
      name: switcher-slack-app
  - secretRef:
      name: switcher-slack-app

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  service:
    type: ClusterIP
    port: 5000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}
