name: Pre Lint and Test Charts
run-name: Pre lint/test - triggered by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      setup-helm-version:
        description: 'azure/setup-helm'
        required: true
        default: 'v4.3.0'
      helm-version:
        description: 'helm/chart-testing-action [helm version]'
        required: true
        default: 'v3.13.3'
      setup-python-version:
        description: 'actions/setup-python'
        required: true
        default: '3.13'
      chart-testing-action-version:
        description: 'helm/chart-testing-action'
        required: true
        default: 'v2.7.0'
      kind-action-version:
        description: 'helm/kind-action'
        required: true
        default: 'v1.12.0'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@${{ github.event.inputs.setup-helm-version }}
        with:
          version: ${{ github.event.inputs.helm-version }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.setup-python-version }}
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@${{ github.event.inputs.chart-testing-action-version }}

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@${{ github.event.inputs.kind-action-version }}

      - name: Run chart-testing (install)
        run: ct install --target-branch ${{ github.event.repository.default_branch }}