name: Pre Lint and Test Charts
run-name: Pre lint/test - triggered by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      setup-python-version:
        description: 'actions/setup-python'
        required: true
        default: '3.13'
      setup-helm-version:
        description: 'azure/setup-helm'
        required: true
        default: 'v3.13.3'
      charts:
        description: 'List of charts to lint/test'
        required: true
        default: 'charts/switcher-api,charts/switcher-gitops,charts/switcher-slack-app'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: ${{ github.event.inputs.setup-helm-version }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.setup-python-version }}
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        run: |
          ct lint --target-branch ${{ github.event.repository.default_branch }} --charts ${{ github.event.inputs.charts }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Run chart-testing (install)
        run: |
          ct install --target-branch ${{ github.event.repository.default_branch }} --charts ${{ github.event.inputs.charts }}