apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: switcher-slack-app
  labels:
    {{- include "switcher-slack-app.labels" . | nindent 4 }}
data:
  SLACK_CLIENT_ID: {{ default "[CHANGE_ME]" .Values.app.env.slackClientId | quote }}
  SWITCHER_URL: {{ .Values.app.env.switcherManagementUrl | quote }}
  SWITCHER_API_URL: {{ .Values.app.env.switcherAPIUrl | quote }}