apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: switcher-slack-app
  labels:
    {{- include "switcher-slack-app.labels" . | nindent 4 }}
type: Opaque
data:
  SLACK_SIGNING_SECRET: {{ default "[CHANGE_ME]" .Values.app.env.slackSigningSecret | b64enc | quote }}
  SLACK_CLIENT_SECRET: {{ default "[CHANGE_ME]" .Values.app.env.slackClientSecret | b64enc | quote }}
  SWITCHER_JWT_SECRET: {{ default "[CHANGE_ME]" .Values.app.env.switcherJwtSecret | b64enc | quote }}