apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: switcher-slack-app
  labels:
    {{- include "switcher-slack-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "switcher-slack-app.selectorLabels" . | nindent 4 }}
